apiVersion: v1
kind: Service
metadata:
  name: tenant-manager
  namespace: serphona
  labels:
    app: tenant-manager
    component: backend
    tier: service
spec:
  type: ClusterIP
  selector:
    app: tenant-manager
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-manager-grpc
  namespace: serphona
  labels:
    app: tenant-manager
    component: backend
    tier: service
    protocol: grpc
spec:
  type: ClusterIP
  selector:
    app: tenant-manager
  ports:
  - name: grpc
    port: 9090
    targetPort: grpc
    protocol: TCP
  sessionAffinity: None
