apiVersion: v1
kind: Service
metadata:
  name: tools-manager
  namespace: serphona
  labels:
    app: tools-manager
    component: backend
spec:
  type: ClusterIP
  selector:
    app: tools-manager
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
