apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: serphona
  labels:
    app: billing-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  selector:
    app: billing-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: billing-service-headless
  namespace: serphona
  labels:
    app: billing-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: billing-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
