apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service
  namespace: serphona
  labels:
    app: billing-service
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: billing-service
  namespace: serphona
  labels:
    app: billing-service
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: billing-service
  namespace: serphona
  labels:
    app: billing-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: billing-service
subjects:
  - kind: ServiceAccount
    name: billing-service
    namespace: serphona
