// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tenantpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TenantServiceClient is the client API for TenantService service.
type TenantServiceClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	ActivateTenant(ctx context.Context, in *ActivateTenantRequest, opts ...grpc.CallOption) (*ActivateTenantResponse, error)
	SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*SuspendTenantResponse, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/CreateTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/GetTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*UpdateTenantResponse, error) {
	out := new(UpdateTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/UpdateTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/DeleteTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/ListTenants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) ActivateTenant(ctx context.Context, in *ActivateTenantRequest, opts ...grpc.CallOption) (*ActivateTenantResponse, error) {
	out := new(ActivateTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/ActivateTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) SuspendTenant(ctx context.Context, in *SuspendTenantRequest, opts ...grpc.CallOption) (*SuspendTenantResponse, error) {
	out := new(SuspendTenantResponse)
	err := c.cc.Invoke(ctx, "/tenant.v1.TenantService/SuspendTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
type TenantServiceServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	ActivateTenant(context.Context, *ActivateTenantRequest) (*ActivateTenantResponse, error)
	SuspendTenant(context.Context, *SuspendTenantRequest) (*SuspendTenantResponse, error)
}

// UnimplementedTenantServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTenantServiceServer struct {
}

func (UnimplementedTenantServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*UpdateTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedTenantServiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantServiceServer) ActivateTenant(context.Context, *ActivateTenantRequest) (*ActivateTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateTenant not implemented")
}
func (UnimplementedTenantServiceServer) SuspendTenant(context.Context, *SuspendTenantRequest) (*SuspendTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuspendTenant not implemented")
}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tenant.v1.TenantService/CreateTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tenant.v1.TenantService/GetTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Simplified other handlers...

var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.v1.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _TenantService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantService_GetTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tenant.proto",
}

// Stub types for missing request/response messages
type GetTenantRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Id            string
}

func (x *GetTenantRequest) Reset()         {}
func (x *GetTenantRequest) String() string { return "" }
func (*GetTenantRequest) ProtoMessage()    {}
func (x *GetTenantRequest) GetId() string  { return x.Id }

type GetTenantResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Tenant        *Tenant
}

func (x *GetTenantResponse) Reset()             {}
func (x *GetTenantResponse) String() string     { return "" }
func (*GetTenantResponse) ProtoMessage()        {}
func (x *GetTenantResponse) GetTenant() *Tenant { return x.Tenant }

type UpdateTenantRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Id            string
	Name          *string
	Email         *string
}

func (x *UpdateTenantRequest) Reset()         {}
func (x *UpdateTenantRequest) String() string { return "" }
func (*UpdateTenantRequest) ProtoMessage()    {}

type UpdateTenantResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Tenant        *Tenant
}

func (x *UpdateTenantResponse) Reset()         {}
func (x *UpdateTenantResponse) String() string { return "" }
func (*UpdateTenantResponse) ProtoMessage()    {}

type DeleteTenantRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Id            string
}

func (x *DeleteTenantRequest) Reset()         {}
func (x *DeleteTenantRequest) String() string { return "" }
func (*DeleteTenantRequest) ProtoMessage()    {}

type DeleteTenantResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Success       bool
}

func (x *DeleteTenantResponse) Reset()         {}
func (x *DeleteTenantResponse) String() string { return "" }
func (*DeleteTenantResponse) ProtoMessage()    {}

type ListTenantsRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Page          int32
	PageSize      int32
	Status        string
	Search        string
}

func (x *ListTenantsRequest) Reset()         {}
func (x *ListTenantsRequest) String() string { return "" }
func (*ListTenantsRequest) ProtoMessage()    {}

type ListTenantsResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Tenants       []*Tenant
	Total         int64
	Page          int32
	PageSize      int32
	TotalPages    int32
}

func (x *ListTenantsResponse) Reset()         {}
func (x *ListTenantsResponse) String() string { return "" }
func (*ListTenantsResponse) ProtoMessage()    {}

type ActivateTenantRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Id            string
}

func (x *ActivateTenantRequest) Reset()         {}
func (x *ActivateTenantRequest) String() string { return "" }
func (*ActivateTenantRequest) ProtoMessage()    {}

type ActivateTenantResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Tenant        *Tenant
}

func (x *ActivateTenantResponse) Reset()         {}
func (x *ActivateTenantResponse) String() string { return "" }
func (*ActivateTenantResponse) ProtoMessage()    {}

type SuspendTenantRequest struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Id            string
}

func (x *SuspendTenantRequest) Reset()         {}
func (x *SuspendTenantRequest) String() string { return "" }
func (*SuspendTenantRequest) ProtoMessage()    {}

type SuspendTenantResponse struct {
	state         interface{}
	sizeCache     interface{}
	unknownFields interface{}
	Tenant        *Tenant
}

func (x *SuspendTenantResponse) Reset()         {}
func (x *SuspendTenantResponse) String() string { return "" }
func (*SuspendTenantResponse) ProtoMessage()    {}
