// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: proto/tenant.proto

package tenantpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant represents a tenant organization.
type Tenant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug         string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Email        string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone        string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Status       string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Plan         string                 `protobuf:"bytes,7,opt,name=plan,proto3" json:"plan,omitempty"`
	Settings     map[string]string      `protobuf:"bytes,8,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Metadata     map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	BillingEmail string                 `protobuf:"bytes,12,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tenant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tenant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Tenant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *Tenant) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Tenant) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tenant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Tenant) GetBillingEmail() string {
	if x != nil {
		return x.BillingEmail
	}
	return ""
}

// CreateTenantRequest represents the request to create a tenant.
type CreateTenantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email        string          `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone        string          `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Plan         string          `protobuf:"bytes,4,opt,name=plan,proto3" json:"plan,omitempty"`
	BillingEmail string          `protobuf:"bytes,5,opt,name=billing_email,json=billingEmail,proto3" json:"billing_email,omitempty"`
	Metadata     *TenantMetadata `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tenant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateTenantRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateTenantRequest) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *CreateTenantRequest) GetBillingEmail() string {
	if x != nil {
		return x.BillingEmail
	}
	return ""
}

func (x *CreateTenantRequest) GetMetadata() *TenantMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TenantMetadata contains optional tenant metadata.
type TenantMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Industry    string `protobuf:"bytes,1,opt,name=industry,proto3" json:"industry,omitempty"`
	CompanySize string `protobuf:"bytes,2,opt,name=company_size,json=companySize,proto3" json:"company_size,omitempty"`
	Website     string `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
}

func (x *TenantMetadata) Reset() {
	*x = TenantMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tenant_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMetadata) ProtoMessage() {}

func (x *TenantMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMetadata.ProtoReflect.Descriptor instead.
func (*TenantMetadata) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantMetadata) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *TenantMetadata) GetCompanySize() string {
	if x != nil {
		return x.CompanySize
	}
	return ""
}

func (x *TenantMetadata) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

// CreateTenantResponse represents the response after creating a tenant.
type CreateTenantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tenant *Tenant `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
}

func (x *CreateTenantResponse) Reset() {
	*x = CreateTenantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_tenant_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantResponse) ProtoMessage() {}

func (x *CreateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantResponse.ProtoReflect.Descriptor instead.
func (*CreateTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

// Simplified other message types for brevity...
// In production, all messages from the proto file would be here

var File_proto_tenant_proto protoreflect.FileDescriptor

var file_proto_tenant_proto_rawDesc = []byte{}

var (
	file_proto_tenant_proto_rawDescOnce sync.Once
	file_proto_tenant_proto_rawDescData = file_proto_tenant_proto_rawDesc
)

func file_proto_tenant_proto_rawDescGZIP() []byte {
	file_proto_tenant_proto_rawDescOnce.Do(func() {
		file_proto_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_tenant_proto_rawDescData)
	})
	return file_proto_tenant_proto_rawDescData
}

var file_proto_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tenant_proto_goTypes = []interface{}{
	(*Tenant)(nil),               // 0: tenant.v1.Tenant
	(*CreateTenantRequest)(nil),  // 1: tenant.v1.CreateTenantRequest
	(*TenantMetadata)(nil),       // 2: tenant.v1.TenantMetadata
	(*CreateTenantResponse)(nil), // 3: tenant.v1.CreateTenantResponse
}

func init() { file_proto_tenant_proto_init() }
func file_proto_tenant_proto_init() {
	if File_proto_tenant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_tenant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tenant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_tenant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tenant_proto_goTypes,
		DependencyIndexes: []int32{},
		MessageInfos:      file_proto_tenant_proto_msgTypes,
	}.Build()
	File_proto_tenant_proto = out.File
	file_proto_tenant_proto_rawDesc = nil
	file_proto_tenant_proto_goTypes = nil
}
